FROM xthursdayx/gpodder-docker:latest
RUN apk add --no-cache python3 py3-pip py3-virtualenv ffmpeg \
 && python3 -m venv /opt/venv \
 && /opt/venv/bin/pip install -U pip yt-dlp
ENV PATH="/opt/venv/bin:${PATH}"
