#!/usr/bin/env bash
set -euo pipefail

SCRIPTS_DIR="${SCRIPTS_DIR:-/workspace/scripts}"
CONF_DIR="/etc/supervisor/conf.d"
INTERVAL="${AUTO_REGISTER_INTERVAL:-5}"

echo "[auto-register] Observando ${SCRIPTS_DIR} cada ${INTERVAL}s"

while :; do
  shopt -s nullglob

  # Añadir nuevos .py (como STOPPED)
  for f in "${SCRIPTS_DIR}"/*.py; do
    base="$(basename "$f" .py)"
    ini="${CONF_DIR}/${base}.ini"
    if [ ! -f "$ini" ]; then
      echo "[auto-register] add ${base}.py"
      py-manager add "${base}.py" || true
    fi
  done

  # Eliminar entradas de scripts borrados (sólo los generados por nosotros)
  for ini in "${CONF_DIR}"/*.ini; do
    [ -e "$ini" ] || continue
    if grep -q "AUTOGENERATED_BY_PY_RUNNER" "$ini"; then
      name="$(basename "$ini" .ini)"
      if [ ! -f "${SCRIPTS_DIR}/${name}.py" ]; then
        echo "[auto-register] remove ${name}"
        py-manager remove "${name}" || true
      fi
    fi
  done

  sleep "$INTERVAL"
done
